<h1><center> Lecture 1 NumPy notebook </center></h1>

In this notebook you will see NumPy in use. The main purpose of using this notebook is simply to confirm that you can run it and understand what it is doing without difficulty. 

**Questions** are in bold. These are not mandatory or graded, they are simply to encourage you to think how you could answer them.

Contacts are in the first point the TAs:

Cristian Rodriguez Rivero: c.m.rodriguezrivero@uva.nl

Sara Mahdavi Hezavehi: s.mahdavihezavehi@uva.nl 

Reshmi Gopalakrishna Pillai: r.gopalakrishnapillai@uva.nl 

Tom van Sonsbeek: t.j.vansonsbeek@uva.nl 

Jia-Hong Huang: j.huang@uva.nl

or in the second point, the course coordinator

Andrew Brown: a.g.brown@uva.nl

<h1><center> Arrays </center></h1>

In [2]:
import numpy as np

In [3]:
list_of_numbers = [10,11,12,13,14,15,16,17,18]
numpy_array_of_numbers = np.array(list_of_numbers)
numpy_array_of_numbers

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [4]:
another_numpy_array = np.arange(10,19)
another_numpy_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [5]:
print(numpy_array_of_numbers.shape, another_numpy_array.shape)

(9,) (9,)


**Q: Can you make a numpy array of only even numbers between 10 and 20, without using a loop?**

**A**

In [7]:
start_point = 10
end_point = 20

num10_20 = np.arange(start_point, end_point + 1, 1)
num10_20

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

<h1><center> Extracting data </center></h1>

In [8]:
yet_another_numpy_array = np.array([20,21,22,23,24,25,26,27,28,29])
yet_another_numpy_array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
yet_another_numpy_array[5]

25

In [10]:
yet_another_numpy_array[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [11]:
yet_another_numpy_array[:-2]

array([20, 21, 22, 23, 24, 25, 26, 27])

**Q: How would you only select valyes between the "4th from last" to the "2nd from last" entries of this array?**

**A**

In [13]:
yet_another_numpy_array[-4:-1]

array([26, 27, 28])

<h1><center> 2D Arrays </center></h1>

In [14]:
a_numpy_2d_array = np.array([[11,12],[13,14]])
a_numpy_2d_array

array([[11, 12],
       [13, 14]])

In [15]:
a_numpy_2d_array[1,0]

13

In [16]:
a_numpy_2d_array[:,0]

array([11, 13])

**Q: Can you switch the [row,column] indices on this array?**

**A**

In [17]:
np.transpose(a_numpy_2d_array)

array([[11, 13],
       [12, 14]])

<h1><center> Reshaping Arrays </center></h1>

In [18]:
numpy_digits_array = np.arange(0,9)
print(numpy_digits_array, " Shape: ", numpy_digits_array.shape)

[0 1 2 3 4 5 6 7 8]  Shape:  (9,)


In [19]:
numpy_digits_array_2D = numpy_digits_array.reshape([3,3])
print(numpy_digits_array_2D, " Shape: ", numpy_digits_array_2D.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]  Shape:  (3, 3)


In [20]:
numpy_digits_array_2D_back_to_1D = numpy_digits_array_2D.reshape(-1)
print(numpy_digits_array_2D_back_to_1D, " Shape: ", numpy_digits_array_2D_back_to_1D.shape)

[0 1 2 3 4 5 6 7 8]  Shape:  (9,)


In [21]:
numpy_with_extra_dim = np.expand_dims(numpy_digits_array_2D_back_to_1D, 0)
print(numpy_with_extra_dim, " Shape: ", numpy_with_extra_dim.shape)

[[0 1 2 3 4 5 6 7 8]]  Shape:  (1, 9)


**Q:How would you add an extra length one dimension at the end of the numpy_digits_array_2D_back_to_1D to make it shape (9,1)?**

In [24]:
numpy_digits_array_2D_91 = numpy_digits_array_2D_back_to_1D.reshape([9,1])
print(numpy_digits_array_2D_91, " Shape: ", numpy_digits_array_2D_91.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]  Shape:  (9, 1)


<h1><center> Arithmetic </center></h1>

In [25]:
a = np.array([[10,11],[12,13]])
b = np.array([[1,-1],[-1,1]])
print("a:\n", a)
print("b:\n", b)

a:
 [[10 11]
 [12 13]]
b:
 [[ 1 -1]
 [-1  1]]


In [26]:
print("a*b:\n", a*b)
print("a+b:\n", a+b)

a*b:
 [[ 10 -11]
 [-12  13]]
a+b:
 [[11 10]
 [11 14]]


In [27]:
print("Matrix multiplication of a and b:\n",np.matmul(a,b))

Matrix multiplication of a and b:
 [[-1  1]
 [-1  1]]


**Q: Can you get the determinant of these matrices?**

**A**

In [28]:
np.linalg.det(a)

-2.000000000000014

In [29]:
np.linalg.det(b)

0.0

<h1><center> Broadcasting </center></h1>

In [30]:
a = np.array([2.0, 4.0, 6.0])
b = np.array([7.0, 8.0, 9.0, 10.0])
print(a,"  ",b)

[2. 4. 6.]    [ 7.  8.  9. 10.]


In [31]:
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [33]:
a.reshape(3,1)

array([[2.],
       [4.],
       [6.]])

In [32]:
a.reshape(3,1)+b

array([[ 9., 10., 11., 12.],
       [11., 12., 13., 14.],
       [13., 14., 15., 16.]])

In [34]:
a+b[:3]

array([ 9., 12., 15.])

<h1><center> Random Variables </center></h1>

In [35]:
print("1 random uniform number:\n", np.random.uniform(low=0,high=1))
print("3 random uniform numbers:\n", np.random.uniform(low=0,high=1,size=3))

1 random uniform number:
 0.411903546653137
3 random uniform numbers:
 [0.08653898 0.83046027 0.87534587]


In [36]:
print("3 random normally distributed numbers:\n", np.random.normal(loc=0.0, scale=1.0,size=3))

3 random normally distributed numbers:
 [ 0.29980947 -0.7343944   0.94995716]


In [43]:
print("3 random Binomially distributed numbers:\n", np.random.binomial(n=1, p=0.5, size=3))

3 random Binomially distributed numbers:
 [1 1 0]


**Q: Can you get get 10 Poisson random variables from a Poisson distribution of mean 1?**

**A**

In [46]:
mean = 1
np.random.poisson(mean, 10)


array([1, 0, 3, 2, 3, 0, 0, 2, 1, 3])